apiVersion: v1
kind: Service
metadata:
  name: netsvcs-dns
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- toYaml .Values.labels | nindent 4 }}
  ports:
  - name: {{ .Values.service.ports.doh.name }}
    port: {{ .Values.service.ports.doh.port }}
    targetPort: http-doh
    protocol: TCP
  - name: {{ .Values.service.ports.dot.name }}
    port: {{ .Values.service.ports.dot.port }}
    targetPort: tcp-dot
    protocol: TCP
  - name: {{ .Values.service.ports.metrics.name }}
    port: {{ .Values.service.ports.metrics.port }}
    targetPort: metrics
    protocol: TCP
