# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hubauth/v1/hubauth.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18hubauth/v1/hubauth.proto\x12\nhubauth.v1\"+\n\x14GetPublicKeysRequest\x12\x13\n\x0b\x61pi_version\x18\x01 \x01(\t\";\n\x14PublicKeySetResponse\x12#\n\x04keys\x18\x01 \x03(\x0b\x32\x15.hubauth.v1.PublicKey\"z\n\tPublicKey\x12\x0b\n\x03kid\x18\x01 \x01(\t\x12\x11\n\talgorithm\x18\x02 \x01(\t\x12\x16\n\x0epublic_key_pem\x18\x03 \x01(\t\x12\x0b\n\x03use\x18\x04 \x01(\t\x12\x0f\n\x07primary\x18\x05 \x01(\x08\x12\x17\n\x0f\x66\x65tched_at_unix\x18\x06 \x01(\x03\x32h\n\x11HubAuthKeyService\x12S\n\rGetPublicKeys\x12 .hubauth.v1.GetPublicKeysRequest\x1a .hubauth.v1.PublicKeySetResponseBBZ@github.com/penguintechinc/tobogganing/proto/hubauth/v1;hubauthv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hubauth.v1.hubauth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/penguintechinc/tobogganing/proto/hubauth/v1;hubauthv1'
  _globals['_GETPUBLICKEYSREQUEST']._serialized_start=40
  _globals['_GETPUBLICKEYSREQUEST']._serialized_end=83
  _globals['_PUBLICKEYSETRESPONSE']._serialized_start=85
  _globals['_PUBLICKEYSETRESPONSE']._serialized_end=144
  _globals['_PUBLICKEY']._serialized_start=146
  _globals['_PUBLICKEY']._serialized_end=268
  _globals['_HUBAUTHKEYSERVICE']._serialized_start=270
  _globals['_HUBAUTHKEYSERVICE']._serialized_end=374
# @@protoc_insertion_point(module_scope)
