# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import hubauth_pb2 as hubauth_dot_v1_dot_hubauth__pb2


class HubAuthKeyServiceStub(object):
    """HubAuthKeyService exposes hub-api's JWT verification key material over
    gRPC (intra-cluster) as a replacement/complement for the REST
    GET /api/v1/auth/public-key poll. The response is JWKS-shaped (a *set*
    of keys, not a single key) from day one so a future signing-algorithm
    rekey (ES256 primary + RS256 legacy verify-only, bake-out window) can be
    represented without a second transport/schema migration — see
    docs/design: hub-api SSO relocation, §6.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPublicKeys = channel.unary_unary(
                '/hubauth.v1.HubAuthKeyService/GetPublicKeys',
                request_serializer=hubauth_dot_v1_dot_hubauth__pb2.GetPublicKeysRequest.SerializeToString,
                response_deserializer=hubauth_dot_v1_dot_hubauth__pb2.PublicKeySetResponse.FromString,
                )


class HubAuthKeyServiceServicer(object):
    """HubAuthKeyService exposes hub-api's JWT verification key material over
    gRPC (intra-cluster) as a replacement/complement for the REST
    GET /api/v1/auth/public-key poll. The response is JWKS-shaped (a *set*
    of keys, not a single key) from day one so a future signing-algorithm
    rekey (ES256 primary + RS256 legacy verify-only, bake-out window) can be
    represented without a second transport/schema migration — see
    docs/design: hub-api SSO relocation, §6.
    """

    def GetPublicKeys(self, request, context):
        """GetPublicKeys returns the current set of JWT verification public keys.
        At most one key is marked `primary` (the currently-active signing key);
        any remaining keys are legacy, verify-only material during a bake-out
        window. Today this returns exactly one RS256 key with primary=true —
        a pure schema/transport addition, no algorithm change.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HubAuthKeyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPublicKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicKeys,
                    request_deserializer=hubauth_dot_v1_dot_hubauth__pb2.GetPublicKeysRequest.FromString,
                    response_serializer=hubauth_dot_v1_dot_hubauth__pb2.PublicKeySetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hubauth.v1.HubAuthKeyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HubAuthKeyService(object):
    """HubAuthKeyService exposes hub-api's JWT verification key material over
    gRPC (intra-cluster) as a replacement/complement for the REST
    GET /api/v1/auth/public-key poll. The response is JWKS-shaped (a *set*
    of keys, not a single key) from day one so a future signing-algorithm
    rekey (ES256 primary + RS256 legacy verify-only, bake-out window) can be
    represented without a second transport/schema migration — see
    docs/design: hub-api SSO relocation, §6.
    """

    @staticmethod
    def GetPublicKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hubauth.v1.HubAuthKeyService/GetPublicKeys',
            hubauth_dot_v1_dot_hubauth__pb2.GetPublicKeysRequest.SerializeToString,
            hubauth_dot_v1_dot_hubauth__pb2.PublicKeySetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
