# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import manager_pb2 as netsvcs_dot_v1_dot_manager__pb2


class ManagerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterServer = channel.unary_unary(
                '/netsvcs.manager.v1.ManagerService/RegisterServer',
                request_serializer=netsvcs_dot_v1_dot_manager__pb2.RegisterServerRequest.SerializeToString,
                response_deserializer=netsvcs_dot_v1_dot_manager__pb2.RegisterServerResponse.FromString,
                )
        self.RefreshToken = channel.unary_unary(
                '/netsvcs.manager.v1.ManagerService/RefreshToken',
                request_serializer=netsvcs_dot_v1_dot_manager__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=netsvcs_dot_v1_dot_manager__pb2.RefreshTokenResponse.FromString,
                )
        self.GetConfig = channel.unary_unary(
                '/netsvcs.manager.v1.ManagerService/GetConfig',
                request_serializer=netsvcs_dot_v1_dot_manager__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=netsvcs_dot_v1_dot_manager__pb2.GetConfigResponse.FromString,
                )
        self.StreamConfigUpdates = channel.unary_stream(
                '/netsvcs.manager.v1.ManagerService/StreamConfigUpdates',
                request_serializer=netsvcs_dot_v1_dot_manager__pb2.StreamConfigUpdatesRequest.SerializeToString,
                response_deserializer=netsvcs_dot_v1_dot_manager__pb2.ConfigUpdate.FromString,
                )
        self.SendHeartbeat = channel.unary_unary(
                '/netsvcs.manager.v1.ManagerService/SendHeartbeat',
                request_serializer=netsvcs_dot_v1_dot_manager__pb2.SendHeartbeatRequest.SerializeToString,
                response_deserializer=netsvcs_dot_v1_dot_manager__pb2.SendHeartbeatResponse.FromString,
                )
        self.ValidateToken = channel.unary_unary(
                '/netsvcs.manager.v1.ManagerService/ValidateToken',
                request_serializer=netsvcs_dot_v1_dot_manager__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=netsvcs_dot_v1_dot_manager__pb2.ValidateTokenResponse.FromString,
                )
        self.CheckIOC = channel.unary_unary(
                '/netsvcs.manager.v1.ManagerService/CheckIOC',
                request_serializer=netsvcs_dot_v1_dot_manager__pb2.CheckIOCRequest.SerializeToString,
                response_deserializer=netsvcs_dot_v1_dot_manager__pb2.CheckIOCResponse.FromString,
                )


class ManagerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterServer(self, request, context):
        """Server registration and token management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Configuration retrieval
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamConfigUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Node health and metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Token and IOC validation (high-frequency operations)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckIOC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterServer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterServer,
                    request_deserializer=netsvcs_dot_v1_dot_manager__pb2.RegisterServerRequest.FromString,
                    response_serializer=netsvcs_dot_v1_dot_manager__pb2.RegisterServerResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=netsvcs_dot_v1_dot_manager__pb2.RefreshTokenRequest.FromString,
                    response_serializer=netsvcs_dot_v1_dot_manager__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=netsvcs_dot_v1_dot_manager__pb2.GetConfigRequest.FromString,
                    response_serializer=netsvcs_dot_v1_dot_manager__pb2.GetConfigResponse.SerializeToString,
            ),
            'StreamConfigUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamConfigUpdates,
                    request_deserializer=netsvcs_dot_v1_dot_manager__pb2.StreamConfigUpdatesRequest.FromString,
                    response_serializer=netsvcs_dot_v1_dot_manager__pb2.ConfigUpdate.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=netsvcs_dot_v1_dot_manager__pb2.SendHeartbeatRequest.FromString,
                    response_serializer=netsvcs_dot_v1_dot_manager__pb2.SendHeartbeatResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=netsvcs_dot_v1_dot_manager__pb2.ValidateTokenRequest.FromString,
                    response_serializer=netsvcs_dot_v1_dot_manager__pb2.ValidateTokenResponse.SerializeToString,
            ),
            'CheckIOC': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckIOC,
                    request_deserializer=netsvcs_dot_v1_dot_manager__pb2.CheckIOCRequest.FromString,
                    response_serializer=netsvcs_dot_v1_dot_manager__pb2.CheckIOCResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'netsvcs.manager.v1.ManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ManagerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/netsvcs.manager.v1.ManagerService/RegisterServer',
            netsvcs_dot_v1_dot_manager__pb2.RegisterServerRequest.SerializeToString,
            netsvcs_dot_v1_dot_manager__pb2.RegisterServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/netsvcs.manager.v1.ManagerService/RefreshToken',
            netsvcs_dot_v1_dot_manager__pb2.RefreshTokenRequest.SerializeToString,
            netsvcs_dot_v1_dot_manager__pb2.RefreshTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/netsvcs.manager.v1.ManagerService/GetConfig',
            netsvcs_dot_v1_dot_manager__pb2.GetConfigRequest.SerializeToString,
            netsvcs_dot_v1_dot_manager__pb2.GetConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamConfigUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/netsvcs.manager.v1.ManagerService/StreamConfigUpdates',
            netsvcs_dot_v1_dot_manager__pb2.StreamConfigUpdatesRequest.SerializeToString,
            netsvcs_dot_v1_dot_manager__pb2.ConfigUpdate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/netsvcs.manager.v1.ManagerService/SendHeartbeat',
            netsvcs_dot_v1_dot_manager__pb2.SendHeartbeatRequest.SerializeToString,
            netsvcs_dot_v1_dot_manager__pb2.SendHeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/netsvcs.manager.v1.ManagerService/ValidateToken',
            netsvcs_dot_v1_dot_manager__pb2.ValidateTokenRequest.SerializeToString,
            netsvcs_dot_v1_dot_manager__pb2.ValidateTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckIOC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/netsvcs.manager.v1.ManagerService/CheckIOC',
            netsvcs_dot_v1_dot_manager__pb2.CheckIOCRequest.SerializeToString,
            netsvcs_dot_v1_dot_manager__pb2.CheckIOCResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
