"""Kubernetes client for applying CiliumNetworkPolicy CRDs.

Applies, updates, and deletes CiliumNetworkPolicy custom resources
generated by the cilium_translator module.
"""

from __future__ import annotations

import os
from dataclasses import dataclass

import structlog

logger = structlog.get_logger()

CILIUM_GROUP = "cilium.io"
CILIUM_VERSION = "v2"
CILIUM_PLURAL = "ciliumnetworkpolicies"


@dataclass(slots=True)
class K8sPolicyClient:
    """Client for managing CiliumNetworkPolicy CRDs in Kubernetes."""

    namespace: str = "tobogganing"
    _api: object = None  # kubernetes.client.CustomObjectsApi

    def _ensure_client(self):
        """Lazy-initialize the Kubernetes client."""
        if self._api is not None:
            return
        try:
            from kubernetes import client, config

            if os.getenv("KUBERNETES_SERVICE_HOST"):
                config.load_incluster_config()
            else:
                config.load_kube_config()
            self._api = client.CustomObjectsApi()
        except Exception as e:
            logger.error("Failed to initialize Kubernetes client", error=str(e))
            raise

    def apply(self, manifest: dict) -> bool:
        """Create or update a CiliumNetworkPolicy."""
        self._ensure_client()
        name = manifest["metadata"]["name"]
        ns = manifest["metadata"].get("namespace", self.namespace)

        try:
            self._api.get_namespaced_custom_object(
                group=CILIUM_GROUP,
                version=CILIUM_VERSION,
                namespace=ns,
                plural=CILIUM_PLURAL,
                name=name,
            )
            # Exists — update
            self._api.replace_namespaced_custom_object(
                group=CILIUM_GROUP,
                version=CILIUM_VERSION,
                namespace=ns,
                plural=CILIUM_PLURAL,
                name=name,
                body=manifest,
            )
            logger.info("Updated CiliumNetworkPolicy", name=name, namespace=ns)
        except Exception:
            # Does not exist — create
            try:
                self._api.create_namespaced_custom_object(
                    group=CILIUM_GROUP,
                    version=CILIUM_VERSION,
                    namespace=ns,
                    plural=CILIUM_PLURAL,
                    body=manifest,
                )
                logger.info("Created CiliumNetworkPolicy", name=name, namespace=ns)
            except Exception as e:
                logger.error("Failed to apply CiliumNetworkPolicy", name=name, error=str(e))
                return False
        return True

    def delete(self, name: str, namespace: str | None = None) -> bool:
        """Delete a CiliumNetworkPolicy by name."""
        self._ensure_client()
        ns = namespace or self.namespace
        try:
            self._api.delete_namespaced_custom_object(
                group=CILIUM_GROUP,
                version=CILIUM_VERSION,
                namespace=ns,
                plural=CILIUM_PLURAL,
                name=name,
            )
            logger.info("Deleted CiliumNetworkPolicy", name=name, namespace=ns)
            return True
        except Exception as e:
            logger.error("Failed to delete CiliumNetworkPolicy", name=name, error=str(e))
            return False

    def list_managed(self, namespace: str | None = None) -> list[dict]:
        """List all CiliumNetworkPolicies managed by tobogganing."""
        self._ensure_client()
        ns = namespace or self.namespace
        try:
            result = self._api.list_namespaced_custom_object(
                group=CILIUM_GROUP,
                version=CILIUM_VERSION,
                namespace=ns,
                plural=CILIUM_PLURAL,
                label_selector="app.kubernetes.io/managed-by=tobogganing-hub-api",
            )
            return result.get("items", [])
        except Exception as e:
            logger.error("Failed to list CiliumNetworkPolicies", error=str(e))
            return []
