{{- if .Values.networkPolicy.defaultDeny }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tobogganing.fullname" . }}-default-deny
  namespace: {{ include "tobogganing.namespace" . }}
  labels:
    {{- include "tobogganing.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
