apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: prod-hub-api
  labels:
    app.kubernetes.io/name: tobogganing
    app.kubernetes.io/component: hub-api
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-hub-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: prod-hub-webui
  labels:
    app.kubernetes.io/name: tobogganing
    app.kubernetes.io/component: hub-webui
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-hub-webui
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
