# Gemfile for iOS build dependencies

source "https://rubygems.org"

gem "fastlane", "~> 2.217"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)