#!/usr/bin/env python3
"""Generate OpenAPI 3.x spec from Quart app and save as YAML.

This script boots the hub_api app, extracts the OpenAPI spec
(generated by quart-schema from @validate_request/@validate_response decorators),
and writes it to openapi/v1.yaml.
"""
from __future__ import annotations

import asyncio
import json
import sys
import yaml
from pathlib import Path

# Add repo root to sys.path so hub_api module can be found
repo_root = Path(__file__).parent.parent
sys.path.insert(0, str(repo_root))


async def generate_spec() -> dict:
    """Generate OpenAPI spec from the Quart app using quart-schema.

    QuartSchema automatically extracts the spec from routes decorated with
    @validate_request/@validate_response, so all registered endpoints are
    included in the generated spec.

    Returns:
        OpenAPI 3.x specification dict.
    """
    # Import here to avoid early module loading issues
    from hub_api.app import create_app

    app = create_app()

    # CRITICAL: module blueprints are mounted inside @app.before_serving
    # (registry.apply_to). A plain app_context() does NOT run before_serving,
    # so the spec would contain only the core routes and miss every module
    # (netsvcs, sase, sdwan, ...). test_app() runs the startup lifecycle, which
    # fires before_serving and mounts all module routes before we read the spec.
    async with app.test_app():
        # Get the QuartSchema extension (registered in app.py)
        if "QUART_SCHEMA" not in app.extensions:
            raise RuntimeError(
                "QuartSchema not initialized on app. "
                "Ensure create_app() calls QuartSchema(app) before returning."
            )

        qs = app.extensions["QUART_SCHEMA"]

        # Call openapi() within a request context to generate the spec from all
        # now-mounted routes.
        async with app.test_request_context("/openapi.json", method="GET"):
            response = await qs.openapi()
            spec = await response.get_json()

        # Ensure required metadata is present
        if "info" not in spec:
            spec["info"] = {}
        if "title" not in spec["info"]:
            spec["info"]["title"] = app.config.get("PRODUCT_NAME", "Hub API")
        if "version" not in spec["info"]:
            spec["info"]["version"] = "1.0.0"

        return spec


async def main() -> int:
    """Generate and write OpenAPI spec.

    Returns:
        Exit code (0 = success, 1 = failure).
    """
    try:
        spec = await generate_spec()

        # Determine output path (relative to repo root)
        repo_root = Path(__file__).parent.parent
        output_path = repo_root / "openapi" / "v1.yaml"
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Write as YAML
        with open(output_path, 'w') as f:
            yaml.dump(spec, f, default_flow_style=False, sort_keys=False)

        print(f"OpenAPI spec generated: {output_path}")
        print(f"Spec version: {spec.get('info', {}).get('version')}")
        print(f"Total paths: {len(spec.get('paths', {}))}")

        return 0
    except Exception as e:
        print(f"Error generating OpenAPI spec: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
