version: 2

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"

output:
  format: colored-line-number

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  gofmt:
    simplify: true

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  golint:
    min-confidence: 0.8

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  depguard:
    rules:
      main:
        deny:
          - pkg: "log"
            desc: "use structured logging with logrus instead"

  errcheck:
    check-type-assertions: true
    check-blank: false

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - goconst
    - gocyclo
    - gocognit
    - lll
    - nakedret
    - prealloc
    - gocritic
    - gochecknoinits
    - gochecknoglobals
    - godox
    - funlen
    - whitespace

  disable:
    - depguard # Can be too restrictive for cross-platform code

severity:
  default-severity: error

# Skip certain linters for files with build tags that handle system-specific code
  exclude-rules:
    # Skip systray related linting errors when CGO is disabled
    - text: "could not import github.com/getlantern/systray"
      linters:
        - typecheck
    - text: "Package ayatana-appindicator3-0.1 was not found"
      linters:
        - typecheck
    # Skip unused imports in build-tag specific files
    - path: "_test\\.go"
      linters:
        - gochecknoglobals
        - gochecknoinits
    # Allow long functions in main and setup code
    - path: "cmd/.*\\.go"
      linters:
        - funlen
    # Allow globals in main package
    - path: "cmd/.*\\.go"
      linters:
        - gochecknoglobals