# Alembic Configuration File for Tobogganing Hub API
# This file contains configuration for Alembic, which manages database migrations
# using SQLAlchemy.

[alembic]
# Path to migration scripts
script_location = migrations

# Template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# Python logging configuration
# Logging level for "sqlalchemy.engine"
sqlalchemy.url = mysql://user:pass@localhost/tobogganing

# Logging configuration
[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
