name = "sasewaddle-website"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Environment variables
[vars]
ENVIRONMENT = "production"
SITE_URL = "https://sasewaddle.com"
GITHUB_URL = "https://github.com/penguintechinc/SASEWaddle"
DOCS_URL = "https://docs.sasewaddle.com"
SALES_EMAIL = "sales@penguintech.io"
VERSION = "1.1.0"
BUILD_TYPE = "production"

# Production environment
[env.production]
name = "sasewaddle-website"

[env.production.vars]
ENVIRONMENT = "production"
SITE_URL = "https://sasewaddle.com"
GITHUB_URL = "https://github.com/penguintechinc/SASEWaddle"
DOCS_URL = "https://docs.sasewaddle.com"
SALES_EMAIL = "sales@penguintech.io"
VERSION = "1.1.0"
BUILD_TYPE = "production"

# Preview environment (for pull requests and staging)
[env.preview]
name = "sasewaddle-website-preview"

[env.preview.vars]
ENVIRONMENT = "preview"
SITE_URL = "https://sasewaddle-website-preview.pages.dev"
GITHUB_URL = "https://github.com/penguintechinc/SASEWaddle"
DOCS_URL = "https://docs-preview.sasewaddle.com"
SALES_EMAIL = "sales@penguintech.io"
VERSION = "1.1.0-preview"
BUILD_TYPE = "preview"