name = "sasewaddle-website"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npm run pages:build"

# Environment variables
[vars]
ENVIRONMENT = "production"
SITE_URL = "https://sasewaddle.com"
GITHUB_URL = "https://github.com/penguintechinc/SASEWaddle"
DOCS_URL = "https://docs.sasewaddle.com"
SALES_EMAIL = "sales@penguintech.io"
VERSION = "1.1.0"
BUILD_TYPE = "production"

# Production environment
[env.production]
name = "sasewaddle-website"

[env.production.vars]
ENVIRONMENT = "production"
SITE_URL = "https://sasewaddle.com"
GITHUB_URL = "https://github.com/penguintechinc/SASEWaddle"
DOCS_URL = "https://docs.sasewaddle.com"
SALES_EMAIL = "sales@penguintech.io"
VERSION = "1.1.0"
BUILD_TYPE = "production"

# Staging environment
[env.staging]
name = "sasewaddle-website-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
SITE_URL = "https://sasewaddle-website-staging.pages.dev"
GITHUB_URL = "https://github.com/penguintechinc/SASEWaddle"
DOCS_URL = "https://docs-staging.sasewaddle.com"
SALES_EMAIL = "sales@penguintech.io"
VERSION = "1.1.0-staging"
BUILD_TYPE = "staging"

# Development environment
[env.development]
name = "sasewaddle-website-dev"

[env.development.vars]
ENVIRONMENT = "development"
SITE_URL = "https://sasewaddle-website-dev.pages.dev"
GITHUB_URL = "https://github.com/penguintechinc/SASEWaddle"
DOCS_URL = "https://docs-dev.sasewaddle.com"
SALES_EMAIL = "sales@penguintech.io"
VERSION = "1.1.0-dev"
BUILD_TYPE = "development"