apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: manager-hpa
  namespace: sasewaddle
  labels:
    app.kubernetes.io/name: sasewaddle
    app.kubernetes.io/component: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: manager
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 60
---
# Note: Headend cannot be horizontally scaled due to WireGuard interface constraints
# For high availability, use multiple headend deployments in different regions
# with separate WireGuard networks and load balancing at the DNS level