{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tobogganing.fullname" . }}-hub-api
  namespace: {{ include "tobogganing.namespace" . }}
  labels:
    {{- include "tobogganing.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub-api
spec:
  selector:
    matchLabels:
      {{- include "tobogganing.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: hub-api
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.prometheus.scrapeInterval }}
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ include "tobogganing.namespace" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tobogganing.fullname" . }}-hub-router
  namespace: {{ include "tobogganing.namespace" . }}
  labels:
    {{- include "tobogganing.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub-router
spec:
  selector:
    matchLabels:
      {{- include "tobogganing.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: hub-router
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.monitoring.prometheus.scrapeInterval }}
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ include "tobogganing.namespace" . }}
{{- end }}
