name: Go Build and Release

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-native-client:
    name: Build Native Client Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Desktop platforms
          - goos: darwin
            goarch: amd64
            binary_name: sasewaddle-client-darwin-amd64
          - goos: darwin
            goarch: arm64
            binary_name: sasewaddle-client-darwin-arm64
          - goos: linux
            goarch: amd64
            binary_name: sasewaddle-client-linux-amd64
          - goos: linux
            goarch: arm64
            binary_name: sasewaddle-client-linux-arm64
          - goos: windows
            goarch: amd64
            binary_name: sasewaddle-client-windows-amd64.exe
          # Embedded platforms
          - goos: linux
            goarch: arm
            goarm: 7
            binary_name: sasewaddle-client-linux-armv7
          - goos: linux
            goarch: arm
            goarm: 6
            binary_name: sasewaddle-client-linux-armv6
          - goos: linux
            goarch: mips
            binary_name: sasewaddle-client-linux-mips
          - goos: linux
            goarch: mipsle
            binary_name: sasewaddle-client-linux-mipsle
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Install dependencies
        working-directory: ./clients/native
        run: |
          go mod download
          go mod verify
      
      - name: Build binary
        working-directory: ./clients/native
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-w -s -X main.Version=${{ github.ref_name }}" \
            -o ../../dist/${{ matrix.binary_name }} \
            ./cmd/client
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary_name }}
          path: dist/${{ matrix.binary_name }}

  build-headend-proxy:
    name: Build Headend Proxy Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            binary_name: headend-proxy-linux-amd64
          - goos: linux
            goarch: arm64
            binary_name: headend-proxy-linux-arm64
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Install dependencies
        working-directory: ./headend
        run: |
          go mod download
          go mod verify
      
      - name: Build binary
        working-directory: ./headend
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
        run: |
          go build -ldflags="-w -s -X main.Version=${{ github.ref_name }}" \
            -o ../dist/${{ matrix.binary_name }} \
            ./proxy
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary_name }}
          path: dist/${{ matrix.binary_name }}

  create-universal-binary:
    name: Create macOS Universal Binary
    needs: build-native-client
    runs-on: macos-latest
    
    steps:
      - name: Download Intel binary
        uses: actions/download-artifact@v4
        with:
          name: sasewaddle-client-darwin-amd64
          path: ./
      
      - name: Download ARM64 binary
        uses: actions/download-artifact@v4
        with:
          name: sasewaddle-client-darwin-arm64
          path: ./
      
      - name: Create Universal Binary
        run: |
          lipo -create -output sasewaddle-client-darwin-universal \
            sasewaddle-client-darwin-amd64 \
            sasewaddle-client-darwin-arm64
          chmod +x sasewaddle-client-darwin-universal
      
      - name: Upload Universal Binary
        uses: actions/upload-artifact@v4
        with:
          name: sasewaddle-client-darwin-universal
          path: sasewaddle-client-darwin-universal

  release:
    name: Create Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-native-client, build-headend-proxy, create-universal-binary]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      
      - name: Create checksums
        run: |
          cd artifacts
          for dir in */; do
            cd "$dir"
            for file in *; do
              if [ -f "$file" ]; then
                sha256sum "$file" > "$file.sha256"
                mv "$file" "$file.sha256" ../
              fi
            done
            cd ..
          done
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/sasewaddle-client-*
            artifacts/headend-proxy-*
            artifacts/*.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}